---
django_root: "{{ django_checkout_path }}/src"
django_mainapp: "bornhack"
django_debug: 'False'
django_nginx_static_root: "{{ django_root }}/static/"
django_github_repo_url: "https://github.com/bornhack/bornhack-website"
django_github_branch: "main"
django_media_root: "/storage/django_media_root"
django_media_root_subdirs:
  - "proforma_invoices"
  - "invoices"
  - "creditnotes"
  - "public"
  - "accountingexports"

django_extra_os_dependencies:
  - "jpeg-turbo"
  - "webfonts"
  - "gdal"
  - "geos"
  - "libxslt"
  - "rust"
  - "coin-or-cbc"
  - "cmake"
  - "ninja"
  - "pango"
  - "gobject-introspection"

django_admins: |
  (
      ('bornhack sysadm', 'sysadm@bornhack.org'),
  )
django_timezone: 'Europe/Copenhagen'

supervisord_extra_programs:
  - name: "redis"
    comment: "run redis"
    command: "/usr/local/bin/redis-server /usr/local/etc/redis.conf"
    user: "535" # 535 is the redis uid on freebsd
    priority: "1"

  - name: "invoiceworker"
    comment: "run invoiceworker"
    command: "{{ django_virtualenv_path }}/bin/python -u {{ django_root }}/manage.py run_managepy_worker --sleep 30 shop.invoiceworker"
    user: "www"
    priority: "4"
    environment:
      HOME: ""

  - name: "outgoingemailworker"
    comment: "run outgoingemailworker"
    command: "{{ django_virtualenv_path }}/bin/python -u {{ django_root }}/manage.py run_managepy_worker --sleep 30 utils.outgoingemailworker"
    user: "www"
    priority: "4"
    environment:
      HOME: ""

  - name: "ircworker"
    comment: "run ircworker"
    command: "{{ django_virtualenv_path }}/bin/python -u {{ django_root }}/manage.py run_managepy_worker --sleep 10 ircbot.ircworker"
    user: "www"
    priority: "4"
    environment:
      HOME: ""

pdf_archive_path: '/storage/pdf_archive/'
pdf_test_mode: 'True'

iban: "DK0398600000747866"
swiftbic: "MISPDK21"
regno: 1684
accountno: 747866
bank_name: "Middelfart Sparekasse"

django_sendfile_url: "/public"
django_sendfile_backend: "sendfile.backends.nginx"

django_channels_layer_redis: True
django_channels_backend: "channels_redis.core.RedisChannelLayer"


