---
django_root: "{{ django_checkout_path }}/src"
django_mainapp: "bma"
django_debug: 'False'
django_nginx_static_root: "{{ django_root }}/static/"
django_github_repo_url: "https://github.com/bornhack/bma"
django_github_branch: "develop"
django_pip_requirements_path: "{{ django_root }}/requirements/production.txt"
django_media_root: "/storage/django_media_root"
django_media_root_subdirs:
  - "photos"

django_admins: |
  (
      ('bornhack sysadm', 'sysadm@bornhack.org'),
  )
django_timezone: 'Europe/Copenhagen'

django_extra_os_dependencies:
  - "jpeg-turbo"
  - "webp"
  - "sqlite3"

django_nginx_proxy: true
