---

nginx_proxy: True
nginx_v4_proxy_ip: "10.1.0.9"
vhosts:
  blackbox1:
    vhost_v6ip: "2a09:94c4:55d1:76a0::9"
    hostnames:
      - "blackbox2.servers.bornhack.org"
    default_vhost: True
    locationslash: "{{ blackbox_nginx_locationslash }}"


blackbox_exporter_modules:
  icmp4-3s-100b:
    prober: "icmp"
    timeout: 3s
    icmp:
      source_ip_address: "127.0.0.1"
      payload_size: 100

  http_2xx:
    prober: "http"
    timeout: "5s"
    http:
      method: "GET"

  smtp_starttls:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^220 ([^ ]+) ESMTP (.+)$"
        - send: "EHLO prober"
        - expect: "^250-STARTTLS"
        - send: "STARTTLS"
        - expect: "^220"
        - starttls: true
        - send: "EHLO prober"
        - expect: "^250-AUTH"
        - send: "QUIT"

  dovecot_tls:
    prober: tcp
    timeout: 5s
    tcp:
      tls: true
      query_response:
        - expect: "Dovecot ready.$"
