---
prometheus_monitor_name: "prometheus1"
prometheus_external_url: "https://prometheus.bornhack.org"

prometheus_alertmanager_configs:
  - scheme: "https"
    static_configs:
      - targets:
        - "alertmanager.bornhack.org:443"

# we use info,warning,error,critical for the severity label
prometheus_alertmanager_rules:
  - name: "bornhack-probe-group"
    rules:
      - alert: "probe_not_up"
        expr: "up == 0"
        for: "10m"
        labels:
          severity: "critical"
        annotations:
          summary: "One or more probes are not up. Check the affected services!"
      - alert: "probe_unsuccessful"
        expr: "probe_success == 0"
        for: "10m"
        labels:
          severity: "critical"
        annotations:
          summary: "One or more probes failed. Check the affected services!"
  - name: "bornhack-certificate-group"
    rules:
      - alert: "https_certificate_too_old"
        expr: "((probe_ssl_earliest_cert_expiry - time()) / 60 / 60 / 24) < 29"
        labels:
          severity: "warning"
        annotations:
          summary: "The target certificate expires in 28 days or less, check certgrinder status"
      - alert: "https_certificate_way_too_old"
        expr: "((probe_ssl_earliest_cert_expiry - time()) / 60 / 60 / 24) < 10"
        labels:
          severity: "critical"
        annotations:
          summary: "The target certificate expires in 10 days or less, check certgrinder status"
  - name: "bornhack-pkg-group"
    rules:
      - alert: "vulnerable_packages_installed"
        expr: "pkg_vulnerable_packages_total > 0"
        labels:
          severity: "critical"
        annotations:
          summary: "The host has one or more vulnerable packages installed"
      - alert: "pkg_multiple_freebsd_versions_installed"
        expr: "count by (instance) (pkg_packages_freebsd_version_total) > 1"
        labels:
          severity: "critical"
        annotations:
          summary: "The host has packages from more than one FreeBSD version (__FreeBSD_version) installed. Maybe a missing 'pkg autoremove && pkg upgrade -f' after OS upgrade? Check '/usr/sbin/pkg annotate --all --show FreeBSD_version' for details."

prometheus_recording_rules:
  - name: "modem-exporter-group"
    rules:
      - record: "mobile_modem_atcsq_dbm"
        expr: "(mobile_modem_atcsq_rssi * 2) - 113"

blackbox2_relabel: &blackbox2_relabel
  - source_labels:
      - '__address__'
    target_label: '__param_target'
  - source_labels:
      - '__param_target'
    target_label: 'instance'
  - target_label: '__address__'
    replacement: 'blackbox2.servers.bornhack.org:9999'

prometheus_scrape_configs:
  - name: 'bornhack-http-services'
    scheme: 'https'
    scrape_interval: '10s'
    metrics_path: "/proxy"
    params:
      module:
        - "blackbox_exporter"
        - "http_2xx"
    targets:
      - "bornhack.dk"
      - "wwwstaging.bornhack.org"
      - "mail.bornhack.org"
      - "people.bornhack.org/tyk"
    relabel_configs: *blackbox2_relabel

  - name: 'bornhack-imap-service'
    scheme: 'https'
    scrape_interval: '10s'
    metrics_path: "/proxy"
    params:
      module:
        - "blackbox_exporter"
        - "dovecot_tls"
    targets:
      - "imap.bornhack.org:993"
    relabel_configs: *blackbox2_relabel

  - name: 'bornhack-smtp-service'
    scheme: 'https'
    scrape_interval: '10s'
    metrics_path: "/proxy"
    params:
      module:
        - "blackbox_exporter"
        - "smtp_starttls"
    targets:
      - "mail.bornhack.org:25"
      - "mail.bornhack.org:587"
    relabel_configs: *blackbox2_relabel

  - name: "expexp"
    scheme: "https"
    scrape_interval: "10s"
    targets:
      - "nuc1.servers.bornhack.org:9999"
      - "alertmanager2.servers.bornhack.org:9999"
      - "ansible3.servers.bornhack.org:9999"
      - "blackbox2.servers.bornhack.org:9999"
      - "container1.servers.bornhack.org:19999"
      - "dns1.servers.bornhack.org:9999"
      - "grafana2.servers.bornhack.org:9999"
      - "imap3.servers.bornhack.org:9999"
      - "people3.servers.bornhack.org:9999"
      - "prometheus2.servers.bornhack.org:9999"
      - "postgres1.servers.bornhack.org:9999"
      - "smtp2.servers.bornhack.org:9999"
      - "syslog1.servers.bornhack.org:9999"
      - "tor3.servers.bornhack.org:9999"
      - "webproxy3.servers.bornhack.org:9999"
      - "django4.servers.bornhack.org:9999"
      - "django5.servers.bornhack.org:9999"
      - "django6.servers.bornhack.org:9999"
      - "django7.servers.bornhack.org:9999"

  - name: "node_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "node_exporter"
    targets:
      - "nuc1.servers.bornhack.org:9999"
      - "alertmanager2.servers.bornhack.org:9999"
      - "ansible3.servers.bornhack.org:9999"
      - "blackbox2.servers.bornhack.org:9999"
      - "container1.servers.bornhack.org:19999"
      - "dns1.servers.bornhack.org:9999"
      - "grafana2.servers.bornhack.org:9999"
      - "imap3.servers.bornhack.org:9999"
      - "people3.servers.bornhack.org:9999"
      - "prometheus2.servers.bornhack.org:9999"
      - "postgres1.servers.bornhack.org:9999"
      - "smtp2.servers.bornhack.org:9999"
      - "syslog1.servers.bornhack.org:9999"
      - "tor3.servers.bornhack.org:9999"
      - "webproxy3.servers.bornhack.org:9999"
      - "django4.servers.bornhack.org:9999"
      - "django5.servers.bornhack.org:9999"
      - "django6.servers.bornhack.org:9999"
      - "django7.servers.bornhack.org:9999"

  - name: "uwsgi_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "uwsgi_exporter"
    targets:
      - "django4.servers.bornhack.org:9999"
      - "django5.servers.bornhack.org:9999"
      - "django6.servers.bornhack.org:9999"
      - "django7.servers.bornhack.org:9999"


  - name: "nginx_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "nginx_exporter"
    targets:
      - "alertmanager2.servers.bornhack.org:9999"
      - "blackbox2.servers.bornhack.org:9999"
      - "grafana2.servers.bornhack.org:9999"
      - "people3.servers.bornhack.org:9999"
      - "prometheus2.servers.bornhack.org:9999"
      - "smtp2.servers.bornhack.org:9999"
      - "webproxy3.servers.bornhack.org:9999"
      - "django4.servers.bornhack.org:9999"
      - "django5.servers.bornhack.org:9999"
      - "django6.servers.bornhack.org:9999"
      - "django7.servers.bornhack.org:9999"

  - name: "gstat_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "gstat_exporter"
    targets:
      - "container1.servers.bornhack.org:19999"
      - "nuc1.servers.bornhack.org:9999"

  - name: "sysctl_exporter"
    scheme: "https"
    scrape_interval: "60s"
    metrics_path: "/proxy"
    params:
      module:
        - "sysctl_exporter"
    targets:
      - "container1.servers.bornhack.org:19999"
      - "nuc1.servers.bornhack.org:9999"

  - name: "jail_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "jail_exporter"
    targets:
      - "container1.servers.bornhack.org:19999"
      - "nuc1.servers.bornhack.org:9999"

  - name: "nut_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "nut_exporter"
    targets:
      - "container1.servers.bornhack.org:19999"

  - name: "smokeping_prober_fib0"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "smokeping_prober_fib0"
    targets:
      - "container1.servers.bornhack.org:19999"
      - "nuc1.servers.bornhack.org:9999"
    labels:
      fib: "0"

  - name: "smokeping_prober_fib1"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "smokeping_prober_fib1"
    targets:
      - "container1.servers.bornhack.org:19999"
    labels:
      fib: "1"

  - name: "smokeping_prober_fib2"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "smokeping_prober_fib2"
    targets:
      - "container1.servers.bornhack.org:19999"
    labels:
      fib: "2"

  - name: "django_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/metrics"
    targets:
      - "django4.servers.bornhack.org:9999"
      - "django5.servers.bornhack.org:9999"
      - "django6.servers.bornhack.org:9999"
      - "django7.servers.bornhack.org:9999"

  - name: "pfctl-exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "pfctl-exporter"
    targets:
      - "nuc1.servers.bornhack.org:9999"
      - "container1.servers.bornhack.org:19999"

supervisord_extra_programs:
  - name: "socat_for_container1_prometheus"
    comment: "run socat to tunnel to container1 prometheus exporter_exporter"
    command: "/usr/local/bin/socat tcp-listen:19999,fork,reuseaddr socks4a:127.0.0.1:ezbbgv3dcm6hydlcedsc4funxzfbxr2alivizghtvmboouq4tym2hcyd.onion:9999,socksport=9050"
    user: "nobody"
    priority: "1"

etchosts: |
  # resolve container1 hostname to localhost so prom will use the socat tunnel
  127.0.0.1 container1.servers.bornhack.org


tor_instances:
  main:
    onion_client_auths:
      - name: "container1"
        onion: "ezbbgv3dcm6hydlcedsc4funxzfbxr2alivizghtvmboouq4tym2hcyd"
        privkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38616161376264313062623937373832343539633066616666383339626464306365356633346234
          3636336335316164623838363636643962396535646331340a343561393237353137656235363736
          35313261313132363764643530633839316363653235363964333337366264656238343932313138
          3336363763646336350a643533303866356533646262376539653866653838613833373833353165
          61373830623861303436666633653231393761353539316432623663336234383434656235366537
          65366463313230376533363261313465353436653433396665663332363964613264386531656438
          306637373431336332333539373266643339
