---
nginx_proxy: True
nginx_cache: True
nginx_cache_inactive: "24h"

vhosts:
  webproxy3_servers_bornhack_dk:
    vhost_v6ip: "2a09:94c4:55d1:7682::162"
    hostnames:
      - "webproxy3.servers.bornhack.org"
    default_vhost: True
    locationslash: |
      location /goaccess {
          allow 2a01:3a0:1:1900:10::27;
          deny all;
          alias /usr/local/www/goaccess;
      }
      location = /stub_status {
          stub_status;
          allow 127.0.0.1;
          allow ::1;
          allow 2a09:94c4:55d1:7682::162;
          allow 85.209.118.162;
          deny all;
      }
      location / {
          return 301 https://bornhack.dk/;
      }

  bornhack_dk:
    vhost_v6ip: "2a09:94c4:55d1:7682:162::1"
    hostnames:
      - "bornhack.dk"
      - "www.bornhack.dk"
    locationslash: |
      location / {
          proxy_pass http://django5.servers.bornhack.org:80;
          more_set_headers        "X-Secret-Token: comingsoonish";
      }

  coinifycallback_bornhack_org:
    vhost_v6ip: "2a09:94c4:55d1:7682:162::2"
    hostnames:
      - "coinifycallback.bornhack.org"
    locationslash: |
      location ~ /shop/orders/(?<orderid>[0-9]+)/pay/blockchain/callback/ {
          proxy_set_header        Host bornhack.dk;
          proxy_pass http://django5.servers.bornhack.org:80;
      }
      location / {
        return 301 https://bornhack.dk/;
      }

  wwwstaging_bornhack_org:
    vhost_v6ip: "2a09:94c4:55d1:7682:162::3"
    hostnames:
      - "wwwstaging.bornhack.org"
    locationslash: |
      location / {
          proxy_pass http://django4.servers.bornhack.org:80;
      }

  prometheus_bornhack_org:
    vhost_v6ip: "2a09:94c4:55d1:7682:162::5"
    hostnames:
      - "prometheus.bornhack.org"
    locationslash: |
      location / {
          proxy_pass http://prometheus2.servers.bornhack.org:80;
      }

  alertmanager_bornhack_org:
    vhost_v6ip: "2a09:94c4:55d1:7682:162::6"
    hostnames:
      - "alertmanager.bornhack.org"
    locationslash: |
      location / {
          proxy_pass http://alertmanager2.servers.bornhack.org:80;
      }

  blackbox_bornhack_org:
    vhost_v6ip: "2a09:94c4:55d1:7682:162::7"
    hostnames:
      - "blackbox.bornhack.org"
    locationslash: |
      location / {
          proxy_pass http://blackbox2.servers.bornhack.org:80;
      }

  grafana_bornhack_org:
    vhost_v6ip: "2a09:94c4:55d1:7682:162::8"
    hostnames:
      - "grafana.bornhack.org"
    locationslash: |
      location / {
          proxy_pass http://grafana2.servers.bornhack.org:80;
      }

  mediastaging_bornhack_org:
    vhost_v6ip: "2a09:94c4:55d1:7682:162::9"
    hostnames:
      - "mediastaging.bornhack.org"
    locationslash: |
      location / {
          proxy_pass http://django6.servers.bornhack.org:80;
      }

  media_bornhack_dk:
    vhost_v6ip: "2a09:94c4:55d1:7682:162::a"
    hostnames:
      - "media.bornhack.dk"
    locationslash: |
      location / {
          proxy_pass http://django7.servers.bornhack.org:80;
      }


certgrinder_hostname_sets:
  - "webproxy3.servers.bornhack.org"
  - "bornhack.dk,www.bornhack.dk"
  - "wwwstaging.bornhack.org"
  - "coinifycallback.bornhack.org"
  - "prometheus.bornhack.org"
  - "alertmanager.bornhack.org"
  - "blackbox.bornhack.org"
  - "grafana.bornhack.org"
  - "media.bornhack.dk"
  - "mediastaging.bornhack.org"

goaccess_exclude_ips:
  - "2a09:94c4:55d1:76A0::11"

nginx_exporter_uri: "https://webproxy3.servers.bornhack.org/stub_status"
